### ISSUE TITLE
OMF Not Working

### ISSUE THREAD

**Issue by manojbisht891** [hussainweb/dotfiles-basic-script#2]
Actually when running setup.sh through bootstrap.sh, then after installing oh-my-fish. It never passes control back, instead it opens a fish shell. if we type exit command in that shell, then it passes execution back to the shell, and gives error of "Command OMF not found".

**Comment by hussainweb** [comment]
@manojbisht891, thanks for reporting this and apologies for the delay. I think I have figured out why it happened and fixed it in the most recent commit. If you happen to see it again, please comment here.
